### ISSUE TITLE
Content does not appear

### ISSUE THREAD

**Issue by trfiladelfo** [echodot-llc/Red#1]
Hello,

The content does not appear when marked via programming, it only appears when edited in the tool itself

![image](https://user-images.githubusercontent.com/3305437/77004191-767c4a80-693d-11ea-8a82-008397bf992b.png)

**Comment by echodot-llc** [comment]
Thanks for the report.  I'm trying to replicate this.  Could you list the steps you took that had that result?  

Does `key_string` and `key_hash` also not appear with content?

Could you enter `TYPE key_list` in the console and paste the output here?

**Comment by trfiladelfo** [comment]
I did so,

Python code
`
from redis import Redis
cache_db = Redis('localhost', 6379)
cache_db.lpush('key_list', '1', '2', '3')
`

PrintScreen
![Captura de Tela 2020-03-18 às 18 56 50](https://user-images.githubusercontent.com/3305437/77011378-83536b00-694a-11ea-8489-f766a13d0cb8.png)

Expected result
![image](https://user-images.githubusercontent.com/3305437/77011455-aaaa3800-694a-11ea-82bc-a81f37f97e16.png)

**Comment by trfiladelfo** [comment]
The key_hash and key_list not appear, only key_string.
I tried chance type data, but not work

**Comment by echodot-llc** [comment]
Very helpful.  I tried the code you wrote, but it works on my machine.  

I'm guessing the key panel is collapsed somehow (that's not supposed to be able to happen).  Could you click the "Hide Detail" button and take a screenshot of what happens?

![Screen Shot 2020-03-19 at 7 18 35 AM](https://user-images.githubusercontent.com/53529300/77062323-0e1b8080-69b2-11ea-8ff3-0d1debc4a390.png)

**Comment by echodot-llc** [comment]
I think I just stumbled onto the solution.  It has to do with the split view frame restoration method. 
 I'll have a fix ready today.

**Comment by echodot-llc** [comment]
Fix is included in version 1.4 - released today.  Please update let me know if it works.

https://echodot.com/red/download/

**Comment by echodot-llc** [comment]
Problem still could happen in 1.4.  Should be resolved in 1.4.2.
