### ISSUE TITLE
SSH Key not saved

### ISSUE THREAD

**Issue by scuml** [echodot-llc/Red#11]
When trying to save a connection in favorites that uses an SSH key, it does not save the path to the key.
(Moved from https://github.com/echodot-llc/Kubermagic/issues/1)

**Comment by scuml** [comment]
@bappelt Please subscribe to this issue.

**Comment by scuml** [comment]
This issue is plaguing a handful of users, and when I think I've fixed it, it pops again in later releases.  I believe it is related to Apple's sandboxing/file bookmarks, but I can't see what exactly could be wrong with the implementation.  Everything works fine on my development machines.  

If you **are** or if you **are not** having this issue, please comment below with your machine/OS/Red version so I can get a feel for how widespread the problem is.  

Please also provide screenshots or at least the path which stores your ssh keys.  That might provide some additional clues.

**Comment by bappelt** [comment]
I am having the issue with Red 1.7.1 on a 2018 Macbook Pro running MacOS 11.4. 

The ssh key I am trying to save is at `/Users/bappelt/.ssh/scorebird-staging` which get selected as `~/.ssh/scorebird-staging`

**Comment by mr-j-tree** [comment]
I have this issue with Red 1.7.1, macOS 11.4 on Mac mini (2018).

My ssh key is located in ~/.ssh/some-key-name.pem

**Comment by scuml** [comment]
Thanks for the updates.  Please check out Red 1.7.2 - released today - and let me know if the problem is resolved.

**Comment by mr-j-tree** [comment]
Fixed! It worked straight after updating without me having to reselect the PEM file. It remembered the selection from the previous launch and populated the field - all I had to do was press Connect.

Thanks for the fix, nice work!

**Comment by bappelt** [comment]
Awesome! Worked perfectly for me as well.

**Comment by scuml** [comment]
Great to hear!  Thanks for verifying the fix worked.
