### ISSUE TITLE
Red hangs on connect

### ISSUE THREAD

**Issue by prenagha** [echodot-llc/Red#13]
purchase app yesterday and was working fine
today is just hangs after clicking Connect to redis
redis is up and running
have to force quit app

tried deleting Application Support/Red and Preferences file - still hangs

Please assist

**Comment by echodot-llc** [comment]
Thanks for the report. What version are you running? Do you know if the 1.7.5 upgrade released this week caused the issue?

**Comment by prenagha** [comment]
New user, never used before yesterday. Version 1.7.5
[thread dump here](https://gist.github.com/prenagha/9d35cdf13069c77c6178bf09306db010)

**Comment by prenagha** [comment]
working now

**Comment by scuml** [comment]
Thanks for the update.   If the problem reoccurs, please let me know.
