### ISSUE TITLE
Unable to select SSH key

### ISSUE THREAD

**Issue by mrinella** [echodot-llc/Red#2]
On macOS 10.15.3 and now 10.15.4 with Red version 1.4 (Build 2952) from Mac App Store with commercial license, when I click on icon to select SSH key, nothing happens. Key icon turns blue on click, but fails to open any dialogue. Checked system security and I do not see any entries for Red in any option. This is kind of annoying. How do I fix?

**Comment by echodot-llc** [comment]
Thanks for the report and for purchasing the app.  I was able to replicate the problem you mentioned.  It is specific to Mac OS Catalina.  I'll keep you posted on the progress of the fix.

**Comment by mrinella** [comment]
Thank you.
On Mar 24, 2020, 6:02 PM -0600, Echodot, LLC <notifications@github.com>, wrote:

This email originated from an external source.

Thanks for the report and for purchasing the app. I was able to replicate the problem you mentioned. It is specific to Mac OS Catalina. I'll keep you posted on the progress of the fix.

**Comment by mrinella** [comment]
Fixed for me in 1.4.2. Thank you.

On Mar 24, 2020, at 6:02 PM, Echodot, LLC <notifications@github.com<mailto:notifications@github.com>> wrote:


This email originated from an external source.


Thanks for the report and for purchasing the app. I was able to replicate the problem you mentioned. It is specific to Mac OS Catalina. I'll keep you posted on the progress of the fix.

**Comment by echodot-llc** [comment]
Great to hear.  Just a heads up, there's still an issue I'm addressing with passwords and RSA passcodes that I hope to resolve in the next day or two.  

Thanks again for the bug report and please let me know if any other problems arise.

**Comment by echodot-llc** [comment]
Fixed in 1.4.2

**Comment by echodot-llc** [comment]
Found that saved keys will not work upon reopening app - this is due to Apple's sandboxing restrictions.  Workaround is to select the key again.  Will have another patch ready for this issue soon.
