### ISSUE TITLE
Refresh keys does not always refresh (v2 build 7242)

### ISSUE THREAD

**Issue by mebeingken** [echodot-llc/Red#23]
The option to refresh keys does not always perform its task.

For example, when Red shows this:

<img width="266" alt="Screen Shot 2022-06-07 at 8 23 47 AM" src="https://user-images.githubusercontent.com/19980603/172420145-b2610361-dbe4-4378-b654-2cf88be8125e.png">

And I click the icon to refresh:

<img width="272" alt="Screen Shot 2022-06-07 at 8 23 57 AM" src="https://user-images.githubusercontent.com/19980603/172419956-191c1dc4-14fa-4720-b93e-482916868c50.png">

Nothing changes in Red.

Yet I can see the revised list of keys in redis-cli:

<img width="456" alt="Screen Shot 2022-06-07 at 8 25 17 AM" src="https://user-images.githubusercontent.com/19980603/172420391-09902e3c-9d96-45a0-b1d9-0d3de9ed7a71.png">

Let me know if you need further details!

**Comment by scuml** [comment]
Could you jot down the version of Red and Mac OS version?  Thanks.

**Comment by scuml** [comment]
Great report BTW

**Comment by mebeingken** [comment]
Sorry, should have included here as well as the subject:

<img width="463" alt="Screen Shot 2022-06-07 at 8 33 07 AM" src="https://user-images.githubusercontent.com/19980603/172421487-b10f4f49-5ef8-4bd7-846a-6c9da5d0c614.png">


And here is the OS info:

<img width="424" alt="Screen Shot 2022-06-07 at 8 32 58 AM" src="https://user-images.githubusercontent.com/19980603/172421514-3535b5ce-94a4-4450-9e06-120a2559160b.png">

Thanks for having a look!

**Comment by timchen** [comment]
I'm having the same issue as well. 

Red 2.1 build 7344, running on macOS Monterey, v12.5.1. Interestingly enough I can see/interact with the new Key when I type the name into the Filter text box, but it's not visible otherwise.

**Comment by scuml** [comment]
Solved in version 2.1.1.  Thanks for the reports and for supporting Red.

https://echodot.com/red/download/
