### ISSUE TITLE
Long initial load

### ISSUE THREAD

**Issue by mebeingken** [echodot-llc/Red#24]
On a particular redis server, I have a large (3M+) DB0.  This naturally takes a long time to load. 

However I am often working on DB2, but I'm forced to wait for up to a minute while DB0 loads, and I'm not intending on using it.

To resolve, perhaps save the state of the last DB chosen so that it will persist on startup?

<img width="177" alt="Screen Shot 2022-07-06 at 12 45 30 PM" src="https://user-images.githubusercontent.com/19980603/177631302-89b0b152-a6e2-42bb-af17-24726d97728a.png">

<img width="233" alt="Screen Shot 2022-07-06 at 12 44 55 PM" src="https://user-images.githubusercontent.com/19980603/177631327-845e90a7-1348-4db2-9605-7a60c663c8e2.png">

**Comment by scuml** [comment]
Thanks for the feedback - great idea.

**Comment by scuml** [comment]
I've just released Red 2.1 which adds an Initial/Default Database on connect.  This should let you quickly jump to the database you are using.  

I've also added a feature to name databases within Red.  This allows you to change the name in the app from DB 0 or DB 2 to something that describes what the database contains.  This information is then saved to the Favorite.  

You can download now at https://echodot.com/red/download/ or wait a day or two for the update to appear on the App Store. 

If you find this change helpful, please tell others where you work or in your network about the software.  Thanks!

**Comment by mebeingken** [comment]
This is very helpful. Thanks!
