### ISSUE TITLE
When updating favorite, SSH port is not saved

### ISSUE THREAD

**Issue by gilletty** [echodot-llc/Red#4]
When changing the SSH Port on a favorite and clicking "Save Changes", the SSH Port box reverts to blank.

**Comment by echodot-llc** [comment]
Thanks for the report. I was able to replicate the problem here and create a fix. This will be included in the next release of Red (1.5.2) - out in the next day or two.

**Comment by echodot-llc** [comment]
Red 1.5.2 has been released.

**Comment by gilletty** [comment]
Ports greater than 32767 are not saved (int limitation), so I am still seeing the same issue.

**Comment by echodot-llc** [comment]
You are exactly right.  There were two problems stacked here.  Fixed one, but didn't realize I need an int32 to store all ports.  Are you using the App Store version, or the one from echodot.com?

**Comment by gilletty** [comment]
I’m using the version from echodot.com.

**Comment by echodot-llc** [comment]
Excellent.  Can get the fix into your hands a lot faster through the website.  Just posted 1.5.3 with this fix.

**Comment by gilletty** [comment]
It works now. Thanks!

**Comment by echodot-llc** [comment]
Fantastic - thanks for letting me know.  How's #5 look with this update?
