### ISSUE TITLE
Unable to purchase

### ISSUE THREAD

**Issue by ruralcoder** [echodot-llc/Red#6]
Just downloaded your app from the App Store.  Tried purchasing it, but the UI does not show any options.

<img width="674" alt="Screen Shot 2020-07-13 at 10 27 33 AM" src="https://user-images.githubusercontent.com/12993309/87334471-8f63c980-c4f3-11ea-81d4-1ec85b1367ba.png">

**Comment by echodot-llc** [comment]
Thank you for letting me know.  There was an updated App Store agreement that needed to be agreed to on our end which is causing this.  This should resolve in the next hour or so as Apple processes the agreement.
