### ISSUE TITLE
Crash when connecting to AWS elasticache

### ISSUE THREAD

**Issue by mlilius** [echodot-llc/Red#7]
When connecting when there is only one database with content it works fine. But once there are two or more databases with content it crashes instantly when it connects.
[Red_2020-08-19-202042_Mac-Pro.crash.zip](https://github.com/echodot-llc/Red/files/5099991/Red_2020-08-19-202042_Mac-Pro.crash.zip)

**Comment by echodot-llc** [comment]
Very helpful bug report.  I have found the issue and am working on the patch now.

Send me your email on https://echodot.com/contact/ and I'll get you a license code.  Just write down if you prefer the App Store or the standard off-store version.

**Comment by echodot-llc** [comment]
This has been fixed in 1.5.9 which is ready for download both on and off the Apple Store.
