### ISSUE TITLE
Unable to register app

### ISSUE THREAD

**Issue by nullset** [echodot-llc/Red#8]
Hi I recently purchased Red through a BundleHunt promo. I was sent an app license, but entering the registration key just crashes Red. I'm not sure if the license sent was correctly formatted, however. The instructions in the registration window say to "Include the BEGIN LICENSE and END LICENSE lines" however the license sent via BundleHunt does not include those lines at all. Please help!

**Comment by echodot-llc** [comment]
I've sent an email to you with a properly formatted license key.
