### ISSUE TITLE
SSH MFA broken in 1.6.4

### ISSUE THREAD

**Issue by smaddock** [echodot-llc/Red#9]
We have a second prompt to SSH into our server... Red handled this fine in 1.6.2, but just installed the 1.6.4 update and it hangs at "Waiting for Authorization", never prompts for the second entry, and eventually says:

SSH Tunnel Error
The SSH Tunnel could not authenticate with the remote host. Please check your password and ensure you still have access.

I would try downgrading but I can't find links to older versions.

**Comment by echodot-llc** [comment]
Hi Shawn - 
Thanks for the bug report.  This is a problem with how I compiled the SSH Tunnel binary for M1 chips - need a little time to figure out what I did wrong. 

In the meantime, tunnels still work in 1.6.3 and before - which you can download here... https://s3.amazonaws.com/echodot/red/Red+1.6.3.zip

I'll have a 1.6.5 patch out this week with the tunnel fix and a handful of other improvements as well.

**Comment by echodot-llc** [comment]
@smaddock Please download 1.6.5 (https://echodot.com/red/download/) and let me know if you can now connect.

**Comment by smaddock** [comment]
It's working now! Thanks! :)
